### ISSUE TITLE
Westend & *-Asset-Hub Chains are disabled or not available

### ISSUE THREAD

**Issue by Imod7** [PolkaGate/polkagate-extension#857]
#### Description
After installing the Polkagate extension and creating a new account, I am trying to select the `Westend` or an `* Asset Hub`  (Westend/Polkadot/Kusama Asset Hub) chain and some are disabled or not available depending on the browser I am using.

#### Firefox
- `Westend` appears disabled and 
- any `* Asset Hub` chain is not available as an option 

<img width="364" alt="PolkaGate-Firefox" src="https://github.com/PolkaGate/polkagate-extension/assets/12569221/0a2948bb-0d7d-466d-b516-c9332abd895f">

#### Chrome
- `Westend` and `Westend Asset Hub` appear disabled
- `Polkadot / Kusama Asset Hub` are available

<img width="364" alt="PolkaGate-Chrome" src="https://github.com/PolkaGate/polkagate-extension/assets/12569221/0122f5ca-0d97-409d-a92c-dd66b2112a70">

**Comment by Nick-1979** [comment]
Hi @Imod7 

 In order to utilize testnet chains, you will need to enable them through the settings. Please note that these chains are disabled by default due to the potential for non-consistent changes that may occur within testnets.
 
<img width="367" alt="Screenshot 2023-09-22 at 01 43 24" src="https://github.com/PolkaGate/polkagate-extension/assets/46442452/756de7ce-2f10-439b-a16b-f7011951941a">

**Comment by Imod7** [comment]
Thank you @Nick-1979 for the prompt reply & feedback! 💯 I enabled the testnet chains in `Chrome` through the setting like you indicated and it works. For Firefox that is unfortunate but Chrome is fine also. Closing this issue as resolved.
